[site]
title = "LSG"
description = "LSG 的个人主页，江汉大学。"
favicon = "/favicon.svg"
last_updated = "2026年8月30日"

[author]
name = "LSG"
title = ""
institution = "江汉大学"
avatar = "/avatar.png"

[social]
# Contact information (leave blank or delete to hide)

email = ""
location = "武汉"
location_url = ""
location_details = []
google_scholar = ""
orcid = ""
github = ""
linkedin = ""

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["zh"]
default_locale = "zh"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "fixed"
fixed_locale = "zh"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = false
# Show a language switcher on the top right corner
switcher = false

[i18n.labels]
zh = "中文"

[[navigation]]
title = "关于我"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "简历"
type = "page"
target = "resume"
href = "/resume"
